# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=10)),
                ('desc', models.TextField(default="Hello, I'm a new product.")),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CustomUser')),
            ],
        ),
    ]
